### ISSUE TITLE
Plugboard issue

### ISSUE THREAD

**Issue by cojoj** [ksylvest/enigma#1]
I know main purpose of this project is to create working **Enigma** simulator and I'm trying to achieve the same but in different language and with slightly different approach 😉

I've noticed that if I take your implementation of `Plugboard` it has some differences with the original one. First of all, the original **Enigma** allows only **10 swaps**. This is not a big deal, but for the sake of consistency.  
Another thing, which is more alarming, is the fact that right now you can do something like:
```ruby
plugboard = Enigma::Plugboard()

plugboard.plug('a', 'b')
plugboard.plug('a', 'c')
plugboard.plug('a', 'd')
plugboard.plug('a', 'e')
plugboard.plug('a', 'f')
plugboard.plug('a', 'g')
plugboard.plug('a', 'h')
```

This will create something like **one-to-many** relation but you rather want **one-to-one**, right? Just visualizing it in your mind as physical wires connection two plug-holes is a great help - you can only create connection from one letter to another one.  
This can be solved in two different ways:

1. Throw and error when someone tries to re-set the value and provide a method for unplugging or something like this.
2. Re-set the value without even asking (user should be aware of this).

Hope you don't mind me digging into this, but I find your example clear and well written 👌

**Comment by ksylvest** [comment]
@cojoj You are correct. I think an exception would probably be best - although truthfully this was just a demonstration of the concept and I'm fine with allowing garbage input. If you are interested in adding a pull request I'd happily merge.

**Comment by cojoj** [comment]
@ksylvest I think I'll create a PRR at some point, but let me first try and do mine implementation, so I can come with other _edge cases_ 👌I'm writing **Enigma** in **Swift 2** and trying to get the most of the language itself... Also I want to have a high test coverage and put everything into a framework, so the **Enigma** itself will be reusable component for other applications 😉

**Comment by ksylvest** [comment]
@cojoj Ah, sounds really cool. I've been doing a lot of Swift lately. Send me a link when you get something up - would love to take a look through (PS - how do you think applications would use an Enigma?).

**Comment by cojoj** [comment]
Well, my first idea was to create a custom keyboard, but it turns that only the sky is a limit 😉 You can create a game based on this, simple learning application, or even a chat or something similar...
